### ISSUE TITLE
JDK13/J9/AIX failing with misslng ibmdemangle.h include

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#1397]
**Platform:**
AIX

**Architecture:**
Power

Please describe the issue that you are having with our binaries and if possible how to recreate it.
```                                              ^
In file included from /home/jenkins/workspace/build-scripts/jobs/jdk13u/jdk13u-aix-ppc64-openj9/workspace/build/src/build/aix-ppc64-server-release/vm/compiler/../omr/compiler/ras/CallStack.cpp:44:
/usr/include/demangle.h:137:2: error: "Please include ibmdemangle.h for xlclang++ to demangle symbol names."
#error "Please include ibmdemangle.h for xlclang++ to demangle symbol names."
 ^
    1500-036: (I) The NOSTRICT option (default at OPT(3)) has the potential to alter the semantics of a program.  Please refer to documentation on the STRICT/NOSTRICT option for more information.
10 warnings generated.
8 warnings and 1 error generated.
```
Ref: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk13u/job/jdk13u-aix-ppc64-openj9
Equivalent at https://ci.eclipse.org/openj9/job/Build_JDK13_ppc64_aix_Nightly/ seems ok

**Comment by sxa555** [comment]
It looks like https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk13u/job/jdk13u-aix-ppc64-openj9/ is set to build with an `SCM_REF` of `openj9-0.16.0`. It isn't automatically updating because it is still disabled in https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/jobs/configurations/jdk12u.groovy

**Comment by sxa555** [comment]
Fixed the lock to 0.16.0 and it looks more promising with the latest code.

However, I also had to disable DDR (https://github.com/AdoptOpenJDK/openjdk-build/pull/1399) since that's not currently working on this combination - will be re-enabled at some point (see https://github.com/eclipse/openj9/issues/7612) but will currently cause the build to fail if it's not disabled.

**Comment by sxa555** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk13u/job/jdk13u-aix-ppc64-openj9/ is now passing
