### ISSUE TITLE
"Path name too long" errors in JDK11/hotspot/windows builds

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#1646]
Potentially introduced by https://github.com/AdoptOpenJDK/openjdk-build/pull/1639

Ref: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x86-32-hotspot/464/console / https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x86-32-hotspot/464/console

`c1 : fatal error C1081: 'c:/cygwin64/tmp/openjdk-build/jdk11u-windows-x86-32-hotspot/workspace/build/src/build/windows-x86-normal-clientANDserver-release/support/test/hotspot/jtreg/native/support/libGetOwnedMonitorStackDepthInfoWithEATest/libGetOwnedMonitorStackDepthInfoWithEATest.obj': file name too long`
`

**Comment by gdams** [comment]
@johnoliver looks like we'll need to make it even shorter....

**Comment by gdams** [comment]
for reference the current tmp drive is `c:/cygwin64/tmp/openjdk-build/jdk11u-windows-x86-32-hotspot`

**Comment by gdams** [comment]
in the previous setup we used `/tmp/openjdk-jdk11u-windows-x86-32-hotspot `
